/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import Message.Message;
import chatclient.Client;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author talha
 */
public class ChatScreen extends javax.swing.JFrame {

    /**
     * Creates new form ChatScreen
     */
    public int isUser = 0; // 0 group, 1 user
    public static ChatScreen myChatScreen;

    public ChatScreen() {
        initComponents();
        myChatScreen = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        pnl_main = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_chat = new javax.swing.JTextArea();
        lbl_chat = new javax.swing.JLabel();
        btn_sendMessage = new javax.swing.JButton();
        btn_sendFile = new javax.swing.JButton();
        btn_sendEmoji = new javax.swing.JButton();
        txtb_message = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 370));
        setMinimumSize(new java.awt.Dimension(400, 370));
        setPreferredSize(new java.awt.Dimension(400, 370));
        setSize(new java.awt.Dimension(400, 370));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnl_main.setBackground(new java.awt.Color(204, 255, 204));

        txta_chat.setEditable(false);
        txta_chat.setColumns(20);
        txta_chat.setRows(5);
        jScrollPane1.setViewportView(txta_chat);

        lbl_chat.setForeground(new java.awt.Color(0, 0, 0));
        lbl_chat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_chat.setText("CHAT");

        btn_sendMessage.setText("SEND");
        btn_sendMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendMessageActionPerformed(evt);
            }
        });

        btn_sendFile.setText("ADD FILE");
        btn_sendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendFileActionPerformed(evt);
            }
        });

        btn_sendEmoji.setText("EMOJI");
        btn_sendEmoji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendEmojiActionPerformed(evt);
            }
        });

        btn_back.setText("<");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addGroup(pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_mainLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_mainLayout.createSequentialGroup()
                                .addComponent(txtb_message)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_sendMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_mainLayout.createSequentialGroup()
                                .addComponent(btn_sendFile)
                                .addGap(18, 18, 18)
                                .addComponent(btn_sendEmoji))))
                    .addGroup(pnl_mainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_back)
                        .addGap(29, 29, 29)
                        .addComponent(lbl_chat, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_mainLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_chat)
                    .addComponent(btn_back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_sendMessage)
                    .addComponent(txtb_message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sendFile)
                    .addComponent(btn_sendEmoji))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_main);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btn_sendEmojiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendEmojiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sendEmojiActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_sendMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendMessageActionPerformed
        // TODO add your handling code here:

        if (isUser == 0) {            // group message
            Message msg = new Message(Message.Message_Type.SendGroupName);
            msg.content = lbl_chat.getText();
            Client.Send(msg);
            Message msg2 = new Message(Message.Message_Type.SendGroupMessage);
            msg2.content = txtb_message.getText();
            Client.Send(msg2);

        } else {                     // user message
            Message msg = new Message(Message.Message_Type.SendUserName);
            msg.content = lbl_chat.getText();
            Client.Send(msg);
            String fullMsg = ChatApp.myApp.txtb_userName.getText() + ": " + txtb_message.getText() + "\n";
            int result = ChatApp.myApp.checkUserList(lbl_chat.getText());
            if (result == -1) {
                ChatApp.myApp.userArray.add(lbl_chat.getText());
                ChatApp.myApp.userMessageArray.add(fullMsg);
                txta_chat.setText(fullMsg);
            } else {
                ChatApp.myApp.userMessageArray.set(result, (ChatApp.myApp.userMessageArray.get(result) + fullMsg));
                txta_chat.setText(ChatApp.myApp.userMessageArray.get(result));
            }
            Message msg2 = new Message(Message.Message_Type.SendUserMessage);
            msg2.content = fullMsg;
            Client.Send(msg2);
        }
        txtb_message.setText("");
    }//GEN-LAST:event_btn_sendMessageActionPerformed

    private void btn_sendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendFileActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn_sendFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_sendEmoji;
    private javax.swing.JButton btn_sendFile;
    private javax.swing.JButton btn_sendMessage;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lbl_chat;
    private javax.swing.JPanel pnl_main;
    public javax.swing.JTextArea txta_chat;
    private javax.swing.JTextField txtb_message;
    // End of variables declaration//GEN-END:variables
}
